# Dockerfile fully generated by AI. I did not make this
# Multi-stage build for Go backend and Svelte frontend
FROM node:18-alpine AS frontend-builder

# Set working directory for frontend
WORKDIR /app/frontend

# Copy frontend package files
COPY frontend/package*.json ./
COPY frontend/pnpm-lock.yaml ./

# Install pnpm and frontend dependencies
RUN npm install -g pnpm
RUN pnpm install

# Copy frontend source code
COPY frontend/ ./

# Build frontend
RUN pnpm build

# Go backend build stage
FROM golang:1.24-alpine AS backend-builder

# Install build dependencies
RUN apk add --no-cache git ca-certificates tzdata

# Set working directory for backend
WORKDIR /app

# Copy Go module files
COPY go.mod go.sum ./

# Download Go dependencies
RUN go mod download

# Copy backend source code
COPY . ./

# Build Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/server

# Final runtime stage
FROM alpine:latest

# Install runtime dependencies
RUN apk --no-cache add ca-certificates tzdata

# Create non-root user
RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

# Set working directory
WORKDIR /app

# Copy Go binary from backend stage
COPY --from=backend-builder /app/backend/main ./

# Copy built frontend from frontend stage
COPY --from=frontend-builder /app/frontend/build ./frontend/build

# Create necessary directories and set proper permissions
RUN mkdir -p downloads && \
    chown -R appuser:appgroup downloads && \
    chmod 755 downloads

# Switch to non-root user
USER appuser

# Expose port
EXPOSE 9520

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:9520/ || exit 1

# Run the backend server
CMD ["./main"]
