version: '3.8'

services:
  marchive:
    image: ghcr.io/akramboussanni/marchive:main
    networks:
      - marchive-network
    command: ["sh", "-c", "cd /app/frontend && pnpm start & cd /app/backend && ./main; wait"]
    ports:
      - "9520:9520"  # Backend API
      - "5173:5173"  # Frontend dev server
    environment:
      # CHANGE THESE FOR PRODUCTION:
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - ANNAS_API_KEY=your-annas-api-key-here
      # CHANGE THESE FOR YOUR DOMAIN:
      - FRONTEND_CORS=http://localhost:5173
      - COOKIE_DOMAIN=localhost
      # These can stay as-is:
      - LOGGER_TYPE=zap
      - DB_CONNECTION_STRING=postgresql://marchive:password@db:5432/marchive?sslmode=disable
      - APP_PORT=9520
      - TRUST_PROXY_IP_HEADERS=false
    volumes:
      - ./downloads:/app/backend/downloads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    networks:
      - marchive-network
    environment:
      - POSTGRES_DB=marchive
      - POSTGRES_USER=marchive
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Database port (optional, for debugging)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marchive -d marchive"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  marchive-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
